# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.13-alpine

# Set environment variables to prevent Python from writing .pyc files
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Install build dependencies
RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev curl

# Set the working directory in the container
WORKDIR /app

# Copy project files
COPY pyproject.toml ./
COPY src/*.py ./
COPY README.md ./

# Upgrade pip and install hatchling build tool
RUN pip install --upgrade pip && \
    pip install hatchling

# Install uv (ultra-fast pip alternative)
RUN pip install --no-cache-dir uv

# Build and install the project
RUN pip install .

# Make port 19110 available to the world outside this container
EXPOSE 8000

# Run the command to start uvicorn
CMD ["uvx", "mcpo", "--port", "8000", "--", "uvx", "/app"]


